spring:
  datasource:
    url: jdbc:mysql://localhost/virtualschool?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: docker
    username: root
  jpa:
    generate-ddl: true
    #hibernate:
      #ddl-auto: create
    show-sql: true